Repository gdsc-nits-org/guidance-grid-client, pull requests merged in 2022-11, with the labels that each got.

#4 [added package]: Added Iconify Icon Pack
  package.json
  pnpm-lock.yaml
Labels: enhancement

#7 move iconify from devDep to Dep
  package.json
  pnpm-lock.yaml
Labels: pls-merge

#8 Root Colors
  src/index.scss
Labels: pls-merge

#6 Article Card
  public/articles/getarticles.json
  src/Components/ArticleCard/ArticleCard.jsx
  src/Components/ArticleCard/ArticleCard.module.scss
  src/Components/Loading/Loading.jsx
  src/Components/Loading/Loading.module.scss
  src/Components/TagItem/TagItem.jsx
  src/Components/TagItem/TagItem.module.scss
  src/Components/index.jsx
  src/Pages/Home/Home.jsx
  src/index.scss
Labels: enhancement, pls-merge
