Repository gdsc-nits-org/guidance-grid-client, pull requests merged in 2022-12, with the labels that each got.

#11 ADD: useFetchData hook
  docs/hooks/useFetchData.md
  public/articles/getarticles.json
  src/Components/ArticleCard/ArticleCard.jsx
  src/Components/TagItem/TagItem.jsx
  src/Hooks/index.js
  src/Hooks/useFetchData.js
  src/Pages/Home/Home.jsx
Labels: enhancement, pls-merge

#13 [hotfix] fix Home.module.scss
  src/Pages/Home/Home.module.scss
Labels: pls-merge

#5 Footer
  public/images/logo.svg
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Footer/Footer.module.scss
  src/Components/index.jsx
  src/index.scss
Labels: pls-merge

#15 Navbar
  src/App.jsx
  src/Components/Footer/Footer.module.scss
  src/Components/Navbar/Navbar.jsx
  src/Components/Navbar/Navbar.module.scss
  src/index.scss
  src/main.jsx
  src/routes.jsx
Labels: enhancement, pls-merge

#17 better implementation of navbar toggle
  src/Components/Navbar/Navbar.jsx
Labels: pls-merge

#12 SideBar component
  .map((employee, index) = {
  package.json
  pnpm-lock.yaml
  src/Components/Navbar/Navbar.module.scss
  src/Components/SideBar/SideBar.jsx
  src/Components/SideBar/SideBar.module.scss
  src/Components/SideBar/sidebarData.json
  src/Components/index.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Home/Home.module.scss
Labels: enhancement, dont-merge

#10 Trending Article Section
  .eslintrc.json
  public/articles/trending.json
  public/images/background.png
  public/images/profile.png
  src/Components/Searchbar/Searchbar.jsx
  src/Components/Searchbar/Searchbar.module.scss
  src/Components/SideBar/SideBar.jsx
  src/Components/Trending/Trending.jsx
  src/Components/Trending/Trending.module.scss
  src/Components/index.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Home/Home.module.scss
Labels: dont-merge

#9 Home
  .eslintrc.json
  .map((employee, index) = {
  README.md
  docs/hooks/useFetchData.md
  package.json
  pnpm-lock.yaml
  public/articles/getarticles.json
  public/articles/trending.json
  public/images/background.png
  public/images/logo.svg
  public/images/profile.png
  src/App.jsx
  src/Components/ArticleCard/ArticleCard.jsx
  src/Components/ArticleCard/ArticleCard.module.scss
  src/Components/Footer/Footer.jsx
  src/Components/Footer/Footer.module.scss
  src/Components/Loading/Loading.jsx
  src/Components/Loading/Loading.module.scss
  src/Components/Navbar/Navbar.jsx
  src/Components/Navbar/Navbar.module.scss
  src/Components/Searchbar/Searchbar.jsx
  src/Components/Searchbar/Searchbar.module.scss
  src/Components/SideBar/SideBar.jsx
  src/Components/SideBar/SideBar.module.scss
  src/Components/SideBar/sidebarData.json
  src/Components/TagItem/TagItem.jsx
  src/Components/TagItem/TagItem.module.scss
  src/Components/Trending/Trending.jsx
  src/Components/Trending/Trending.module.scss
  src/Components/index.jsx
  src/Hooks/index.js
  src/Hooks/useEvent.js
  src/Hooks/useFetchData.js
  src/Pages/Error/.gitkeep
  src/Pages/Error/Error.jsx
  src/Pages/Error/Error.module.scss
  src/Pages/Home/Home.jsx
  src/Pages/Home/Home.module.scss
  src/Pages/index.jsx
  src/index.scss
  src/main.jsx
  src/routes.jsx
Labels: dont-merge
