Repository gdsc-nits-org/guidance-grid-client, pull requests merged in 2023-01, with the labels that each got.

#23 ADD: authContext
  .gitignore
  src/Global/Auth/.gitkeep
  src/Global/Auth/AuthProvider.jsx
  src/Global/Auth/authActions.js
  src/Global/Auth/authContext.js
  src/main.jsx
Labels: enhancement, pls-merge

#25 Navbar bugs fixed
  src/Components/Navbar/Navbar.jsx
  src/Components/Navbar/Navbar.module.scss
Labels: pls-merge

#29 Navbar issue fixed
  src/Components/Navbar/Navbar.module.scss
Labels: pls-merge

#24 ADD: Bookmarks Page
  public/articles/bookmarked.json
  public/articles/topwriters.json
  src/App.jsx
  src/Components/BookmarkCard/BookmarkCard.jsx
  src/Components/BookmarkCard/BookmarkCard.module.scss
  src/Components/Searchbar/Searchbar.jsx
  src/Components/TopWriters/TopWriters.jsx
  src/Components/TopWriters/TopWriters.module.scss
  src/Components/index.jsx
  src/Pages/Bookmarks/Bookmark.jsx
  src/Pages/Bookmarks/Bookmark.module.scss
  src/Pages/index.jsx
Labels: enhancement, pls-merge

#35 FIX: use useFetchData hook in SideBar, and fixed overlapping of navbar and sidebar
  public/articles/sidebarData.json
  src/Components/SideBar/SideBar.jsx
  src/Components/SideBar/SideBar.module.scss
  src/Components/SideBar/sidebarData.json
Labels: enhancement, pls-merge

#36 BUGFIX: Prevent selection of next div when double clicking Icon elements
  src/Components/ArticleCard/ArticleCard.jsx
  src/Components/ArticleCard/ArticleCard.module.scss
  src/Components/BookmarkCard/BookmarkCard.jsx
  src/Components/BookmarkCard/BookmarkCard.module.scss
Labels: bug, pls-merge
